
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe3\xc9d\xf5\x12\x05\xc4\x88%\xbc\xb7#w>e\xd3'

_lr_action_items = {'MUL_OP':([4,5,8,9,15,16,17,18,19,],[11,-7,-9,-8,-6,-5,-10,11,11,]),'LEFT_PAREN':([3,6,10,11,13,14,],[6,6,6,6,6,6,]),'EQUALS':([1,],[3,]),'SUB_OP':([4,5,7,8,9,12,15,16,17,18,19,],[-4,-7,13,-9,-8,13,-6,-5,-10,-3,-2,]),'DIV_OP':([4,5,8,9,15,16,17,18,19,],[10,-7,-9,-8,-6,-5,-10,10,10,]),'RIGHT_PAREN':([4,5,8,9,12,15,16,17,18,19,],[-4,-7,-9,-8,17,-6,-5,-10,-3,-2,]),'ADD_OP':([4,5,7,8,9,12,15,16,17,18,19,],[-4,-7,14,-9,-8,14,-6,-5,-10,-3,-2,]),'VAR':([0,3,6,10,11,13,14,],[1,8,8,8,8,8,8,]),'INTEGER':([3,6,10,11,13,14,],[9,9,9,9,9,9,]),'$end':([2,4,5,7,8,9,15,16,17,18,19,],[0,-4,-7,-1,-9,-8,-6,-5,-10,-3,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign_statement':([0,],[2,]),'term':([3,6,13,14,],[4,4,18,19,]),'statement':([3,6,],[7,12,]),'factor':([3,6,10,11,13,14,],[5,5,15,16,5,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign_statement","S'",1,None,None,None),
  ('assign_statement -> VAR EQUALS statement','assign_statement',3,'p_assign_statement','yaccFile.py',13),
  ('statement -> statement ADD_OP term','statement',3,'p_statement_plus','yaccFile.py',17),
  ('statement -> statement SUB_OP term','statement',3,'p_statement_minus','yaccFile.py',21),
  ('statement -> term','statement',1,'p_statement_term','yaccFile.py',25),
  ('term -> term MUL_OP factor','term',3,'p_term_times','yaccFile.py',29),
  ('term -> term DIV_OP factor','term',3,'p_term_div','yaccFile.py',33),
  ('term -> factor','term',1,'p_term_factor','yaccFile.py',37),
  ('factor -> INTEGER','factor',1,'p_factor_num','yaccFile.py',41),
  ('factor -> VAR','factor',1,'p_factor_var','yaccFile.py',45),
  ('factor -> LEFT_PAREN statement RIGHT_PAREN','factor',3,'p_factor_expr','yaccFile.py',52),
]
